### ISSUE TITLE
After installing this user roles page issue arrises

### ISSUE THREAD

**Issue by bhawnam193** [eMagicOne/MagentoStoreManagerConnector#1]
@eMagicOne  when i installed this extension .......My user roles pages when i try to add new page didn't show content just display header and footer. Similarly in the case of edit user role.

**Comment by eMagicOne** [comment]
Hello @bhawnam193 
Thanks for reaching out. 
We would like to check this issue for you from our side. If possible, please, send us your admin access details via contact@mag-manager.com 
Our techs will investigate this issue and get back to you with the result via e-mail.

**Comment by bhawnam193** [comment]
http://emagicone.com/shared_files/magento/magento_2/MagentoStoreManagerConnector_magento_2.zip
new update has issue resolved
