### ISSUE TITLE
Issue with Data on EE 2.1.2

### ISSUE THREAD

**Issue by expandlab** [eMagicOne/MagentoStoreManagerConnector#3]
We are evaluating this plugin for a customer and currently we are having some issues.   We cannot see or manage products or categories.   It's just blank.   We can see other data, such as customers and orders, so I know the connection is present.  

We've tried both with the connector and the FTP methods for connection.

**Comment by eMagicOne** [comment]
Hello. 

Thank you for your message. Please, contact our support via contact@mag-manager.com 
In your e-mail include info on the version of Store Manager you are currently using and your store configuration file (it can be saved in Preferences -> Actions -> Save current configuration). 
Our tech team will check the problem and will get back to you with the result.
