### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by michelve** [eMagicOne/MagentoStoreManagerConnector#4]
{"0":"Please upgrade your database: Run \"bin\/magento setup:upgrade\" from the Magento root directory.\nThe following modules are outdated:\nEmagicone_Bridgeconnector schema: current version - none, required version - 1.0.3\nEmagicone_Bridgeconnector data: current version - none, required version - 1.0.3","1":"#0 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(121): Magento\\Framework\\Module\\Plugin\\DbStatusValidator->beforeDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Magento\\Framework\\App\\Request\\Http))\n#1 \/var\/www\/html\/vendor\/magento\/module-page-cache\/Model\/App\/FrontController\/BuiltinPlugin.php(69): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#2 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch(Object(Magento\\Framework\\App\\FrontController\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#3 \/var\/www\/html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#4 \/var\/www\/html\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#5 \/var\/www\/html\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/html\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#7 \/var\/www\/html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#8 \/var\/www\/html\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#9 {main}","url":"\/odd-eyes-pendulum-dragon-ct12-en001-platinum-secret-rare-limited-edition-ct12-en001-853094.html","script_name":"\/index.php"}

**Comment by eMagicOne** [comment]
Hello! 
Thank you for your comment. 
Please, contact our Support Center via the email contact@mag-manager.com and provide more details on the issue you have faced, so our technical person could check it and advise you on this regard. Waiting to hear from you.

**Comment by eMagicOne** [comment]
For users who face same issue, you should run `php bin/magento setup:upgrade` after module [manual installation](https://store-manager-for-magento-doc.emagicone.com/quick-start-guide/1-magento-store-manager-connector).
