### ISSUE TITLE
Cant install MagentoStoremanagerConnector on Magento 2.3 with php 7.1 

### ISSUE THREAD

**Issue by frilogg** [eMagicOne/MagentoStoreManagerConnector#5]
Installed from extension manager, then trying to run setup:upgrade gets following error

'Emagicone_Bridgeconnector': Installing schema... Deprecated Functionality: Function mcrypt_get_iv_size() is deprecated in ............ /vendor/zendframework/zend-crypt/src/Symmetric/Mcrypt.ph

**Comment by eMagicOne** [comment]
Hello!
Thank you for your message.
Currently, we do not support PHP ver. 7.1, that is why you might have received this error.
Though we are now working on this question and you may also submit a ticket at our official website and we will gladly inform as soon as the compatibility will be added.
Regards.

**Comment by amitjindal** [comment]
Hi @eMagicOne Is this now available with PHP 7.1? Can you provide an estimated date when this will be supported?

**Comment by eMagicOne** [comment]
Hello, Amit! Thank you for your question. It would be appreciated if you contact our support at our official website, so technicians could provide you with more precise answer regarding PHP 7.1.
Best Regards.

**Comment by samybalasa** [comment]
Same problem here, you should resolve urgently, many of us are using 7.1 version and paid version of emagicone software...

**Comment by eMagicOne** [comment]
Hello! 
Thank you for your comment.
Kindly contact our Support Center on the official website to receive the latest version of connector with 7.1 php supported.

**Comment by eMagicOne** [comment]
The issue, related to compatibility with php 7.1 has been fixed for both connector modules, intended for Magento 2.2.x and 2.3.x.
