### ISSUE TITLE
Page 404 After installing the module on magento 2.2.6

### ISSUE THREAD

**Issue by crazymoo070** [eMagicOne/MagentoStoreManagerConnector#6]
hi,

after i installed the plugin i get a 404 error on the backend plugin page only. so i can't connect the store with store manager what can i do ?

**Comment by eMagicOne** [comment]
Hello!
Thank you for letting us know about the issue.
If you have older connector version, (up to 1.0.5)  - update the module and let us know the result.
If the issue occurs on the latest version of connector 1.0.5 - kindly contact our support at the official website, so we could proceed with the investigation. 
Waiting to hear from you.

**Comment by crazymoo070** [comment]
hi,

i didnt had the time. 

but know i updated the plugin and it look likes everything is ok. 

second problem is that i can't not connect with the MagentoStoreManager with error:

Please check at your back-end if your bridge connector module is properly configured and installed

what is the problem i used the username and password that i put in to the plugin settings.

**Comment by eMagicOne** [comment]
Hello,
Thank you for your reply.
We will gladly assist you with the connection setup and for this, kindly contact our support at our official website and provide your store configuration file and admin access details, so our tech person could check the reason of the issue and configure the connection to Magento.
Best Regards.
