### ISSUE TITLE
Undefined index: login

### ISSUE THREAD

**Issue by stoneandstorm** [eMagicOne/MagentoStoreManagerConnector#7]
After a fresh install on a Magento 2.2.6 installation I got the following message when I try to visit the settingpage in the magento backend:

`There has been an error processing your request
Notice: Undefined index: login in /data/web/magento2/vendor/emagicone/module-bridgeconnector/Helper/Tools.php on line 95`

**Comment by eMagicOne** [comment]
Hello!
Thank you for contacting us here.
The message you get is a notice and should not cause any issues with work. Seems, you just have error reporting settings setup to receive all types of messages, including notices. If it causes inconveniences, you can disable notices, check how to make it here - https://stackoverflow.com/questions/2867057/how-do-i-turn-off-php-notices.

**Comment by eMagicOne** [comment]
This inconvenience has been corrected in current version (php 7.1) of the module.
